new post

diff --git a/lb b/lb
--- a/lb
+++ b/lb
@@ -35,7 +35,7 @@ newpost() { read -erp "Give a title for your post:
 	" title
 	echo "$title" | grep -q "\"" && printf "Double quotation marks (\") are not allowed in entry titles.\\n" && exit
 	abs_url="$(echo "$title" | iconv -cf UTF-8 -t UTF-8 | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
-	echo "AddDescription \"$title\" \"$url.md\"" >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
+	echo "AddDescription \"$title\" \"$abs_url.md\"" >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
 
 	( [ -f "$webdir/.drafts/$abs_url/$abs_url.md" ] || [ -d "$webdir/$webtarget/posts/$abs_url" ] ) && echo "There is already an existing draft or post of that same name/URL." && exit
 	mkdir -p "$webdir/.drafts/$abs_url";
@@ -69,9 +69,6 @@ publish() { \
 	cat $tmpdir/html2 > "$article_ref"
 	sed -i "/<!-- LB -->/r $tmpdir/index" "$indexfile"
 	sed -i "/ \"$base.html\"/d" "$archivefile"
-	echo "###########aici"
-	echo $article_ref
-	echo "$webdir/$webtarget/index.html"
 	sed -i "/<div class='articles'>/r $article_ref" "$webdir/$webtarget/index.html"
 	sed -i "/<p>Cele mai recente postari:<\/p>/r $blogfile" "$webdir/$domain_name/index.html"
 	rm "$webdir/$webtarget/posts/$basefile/$basefile.md"
