new post

diff --git a/lb b/lb
--- a/lb
+++ b/lb
@@ -9,6 +9,7 @@ webdir="$(pwd)/Site"
 # The $domain_name variable is to be used twice, as each subdomain has its own dedicated folder.
 blogfile="$webdir/$domain_name/$(date +%Y).html"
 indexfile="$webdir/$domain_name/blogindex.html"
+archivefile="$webdir/.htaccess"
 
 # Variables for publishing
 protocol="https"
@@ -25,6 +26,7 @@ read -erp "Initialize blog in $webdir?" ask &&
 	if [ "$ask" = "y" ]; then
 	printf "Initializing blog system...\\n"
 	mkdir -pv "$webdir/.drafts" || printf "Error. Do you have write permissions in this directory?\\n"
+	echo "Options +Indexes" > "$archivefile"
 else
 	exit
 fi
@@ -33,6 +35,8 @@ newpost() { read -erp "Give a title for your post:
 	" title
 	echo "$title" | grep -q "\"" && printf "Double quotation marks (\") are not allowed in entry titles.\\n" && exit
 	abs_url="$(echo "$title" | iconv -cf UTF-8 -t UTF-8 | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
+	echo "AddDescription \"$title\" \"$url.md\"" >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
+
 
 	( [ -f "$webdir/.drafts/$abs_url/$abs_url.md" ] || [ -f "$webdir/$url/$url.md" ] ) && echo "There is already an existing draft or post of that same name/URL." && exit
 	mkdir -p "$webdir/.drafts/$abs_url";
@@ -52,20 +56,23 @@ listandReturn() {
 
 publish() { \
 	delete draft
+	htaccessentry=$(grep "$basefile" "$archivefile")
+
+	title="$(echo "$htaccessentry" | cut -d'"' -f2)"
 	webdate="$(date '+%a, %d %b %Y %H:%M:%S %z')" # But this visible date you can set to any format.
 	tmpdir=$(mktemp -d)
 	$(cp -r "$webdir/.drafts/$basefile" "$webdir/$webtarget/posts/")
 	$(markdown-to-standalone-html -t "$webdir/$webtarget/template.html" "$webdir/$webtarget/posts/$basefile/$basefile.md" > "$webdir/$webtarget/posts/$basefile/$basefile.html");
-	printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='%s'>standalone</a>]</small>\\n%s...\\n<small>%s</small>\\n</div>\\n" "$base" "$realname" "$website/posts/$basefile/$basefile.html" "$(head -n 2 "$webdir/.drafts/$basefile/$basefile.md" | sed -e 's/#/ /g')" "$webdate" > "$tmpdir/html"
-	printf "<div class='article'>\\n<h3 class='subtitle' id='%s'>%s</h3>\\n<p>%s... <small><a href='%s'>Read more &#187;</a></small> </p> \\n</div>\\n" "$basefile" "$realname" "$(head -n 2 "$webdir/.drafts/$basefile/$basefile.md" | sed -e 's/#/ /g')" "$website/posts/$basefile/$basefile.html"  > "$tmpdir/html2"
+	printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='%s'>standalone</a>]</small>\\n%s...\\n<small>%s</small>\\n</div>\\n" "$base" "$title" "$website/posts/$basefile/$basefile.html" "$(head -n 2 "$webdir/.drafts/$basefile/$basefile.md" | sed -e 's/#/ /g')" "$webdate" > "$tmpdir/html"
+	printf "<div class='article'>\\n<h3 class='subtitle' id='%s'>%s</h3>\\n<p>%s... <small><a href='%s'>Read more &#187;</a></small> </p> \\n</div>\\n" "$basefile" "$title" "$(head -n 2 "$webdir/.drafts/$basefile/$basefile.md" | sed -e 's/#/ /g')" "$website/posts/$basefile/$basefile.html"  > "$tmpdir/html2"
 	printf "<li>%s &ndash; <a href=\"%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$website/posts/$basefile/$basefile.html" "$realname" > "$tmpdir/index"
 	cat $tmpdir/html > "$blogfile"
 	cat $tmpdir/html2 >> "$webtarget_archive_file"
 	sed -i "/<!-- LB -->/r $tmpdir/index" "$indexfile"
+	sed -i "/ \"$base.html\"/d" "$archivefile"
 	article_path=$webdir/$webtarget_archive_file;
 	sed -i "/<div class='articles'>/r $article_path" "$webdir/$webtarget/index.html"
 	sed -i "/<p>Cele mai recente postari:<\/p>/r $blogfile" "$webdir/$domain_name/index.html"
-	rm $article_path;
 	rm "$webdir/$webtarget/posts/$basefile/$basefile.md"
 	rm -rf "$webdir/.drafts/$chosen"
 	push
