working on cleanup

diff --git a/lb b/lb
--- a/lb
+++ b/lb
@@ -1,15 +1,21 @@
 #!/bin/bash
-## Vanilla chocolad
-name="pseudot"
+
+# Config variables
+domain_name="pseudot.org"
+webdir="$(pwd)/Site"
+
+# File structure specific variables
+# The web directory structure uses subdomains
+# The $domain_name variable is to be used twice, as each subdomain has its own dedicated folder.
+blogfile="$webdir/$domain_name/$domain_name/$(date +%Y).html"
+echo $blogfile
+indexfile="$webdir/$domain_name/$domain_name/blogindex.html"
+archivefile="$webdir/$domain_name/.htaccess"
+
+# Variables for publishing
 protocol="https"
-webdir="$PWD"
-webroot="pseudot.xyz/" # Keep a trailing slash.
-www_var_folder_root="pseudot.xyz"
-blogfile="$webdir/$www_var_folder_root/$(date +%Y).html"
-indexfile="$webdir/$www_var_folder_root/blogindex.html"
-archivefile="$webdir/.htaccess"
+gitrepo="andutzu7/pseudot.git"
 gittoken=""
-gitrepo=""
 remotehost=""
 
 
@@ -29,9 +35,10 @@ fi
 newpost() { read -erp "Give a title for your post:
 	" title
 	echo "$title" | grep -q "\"" && printf "Double quotation marks (\") are not allowed in entry titles.\\n" && exit
-	url="$(echo "$title" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
-	echo "AddDescription \"$title\" \"$url.md\"" >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
-	( [ -f "$webdir/.drafts/$url/$url.md" ] || [ -f "$webdir/$url/$url.md" ] ) && echo "There is already an existing draft or post of that same name/URL." && exit
+	abs_url="$(echo "$title" | iconv -cf UTF-8 -t UTF-8 | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g")"
+	echo "AddDescription \"$title\" \"$abs_url.md\"" >>  "$archivefile"|| { echo "Error: Is $archivefile writeable?"; exit; }
+	# cautat de folosit URI
+	( [ -f "$webdir/.drafts/$url<F39><F39><F39><F39><F39><F39><F39>/$abs_url.md" ] || [ -f "$webdir/$url/$url.md" ] ) && echo "There is already an existing draft or post of that same name/URL." && exit
 	mkdir -p "$webdir/.drafts/$url";
 	$EDITOR "$webdir/.drafts/$url/$url.md" ;}
 
@@ -55,9 +62,9 @@ publish() { \
 	tmpdir=$(mktemp -d)
 	$(cp -r "$webdir/.drafts/$basefile" "$webdir/$webtarget/posts/")
 	$(markdown-to-standalone-html -t "$webdir/$webtarget/template.html" "$webdir/$webtarget/posts/$basefile/$basefile.md" > "$webdir/$webtarget/posts/$basefile/$basefile.html");
-	printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='%s'>standalone</a>]</small>\\n%s...\\n<small>%s</small>\\n</div>\\n" "$base" "$realname" "$website/posts/$basefile/$basefile.html" "$(head -n 5 "$webdir/.drafts/$basefile/$basefile.md" | sed -e 's/#/ /g')" "$webdate" > "$tmpdir/html"
-	printf "<div class='article'>\\n<h3 class='subtitle' id='%s'>%s</h3>\\n<p>%s... <small><a href='%s'>Read more &#187;</a></small> </p> \\n</div>\\n" "$base" "$base" "$(head -n 5 "$webdir/.drafts/$basefile/$basefile.md" | sed -e 's/#/ /g')" "$website/posts/$basefile/$basefile.html"  > "$tmpdir/html2"
-	printf "<li>%s &ndash; <a href=\"%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$website/posts/$basefile/$basefile.html" "$base" > "$tmpdir/index"
+	printf "<div class='entry'>\\n<h2 id='%s'>%s</h2>\\n<small>[<a href='%s'>standalone</a>]</small>\\n%s...\\n<small>%s</small>\\n</div>\\n" "$base" "$realname" "$website/posts/$basefile/$basefile.html" "$(head -n 2 "$webdir/.drafts/$basefile/$basefile.md" | sed -e 's/#/ /g')" "$webdate" > "$tmpdir/html"
+	printf "<div class='article'>\\n<h3 class='subtitle' id='%s'>%s</h3>\\n<p>%s... <small><a href='%s'>Read more &#187;</a></small> </p> \\n</div>\\n" "$basefile" "$realname" "$(head -n 2 "$webdir/.drafts/$basefile/$basefile.md" | sed -e 's/#/ /g')" "$website/posts/$basefile/$basefile.html"  > "$tmpdir/html2"
+	printf "<li>%s &ndash; <a href=\"%s\">%s</a></li>\\n" "$(date '+%Y %b %d')" "$website/posts/$basefile/$basefile.html" "$realname" > "$tmpdir/index"
 	cat $tmpdir/html > "$blogfile"
 	cat $tmpdir/html2 > "$webtarget_blog_file"
 	sed -i "/<!-- LB -->/r $tmpdir/index" "$indexfile"
@@ -65,11 +72,12 @@ publish() { \
 	echo "AddDescription \"$realname\" \"$basefile\" "  r>> "$archivefile"
 	article_path=$webdir/$webtarget_blog_file;
 	sed -i "/<div class='articles'>/r $article_path" $webdir/$webtarget/index.html
-	sed -i "/<p>Cele mai recente postari:<\/p>/r $blogfile" $webdir/$www_var_folder_root/index.html
+	sed -i "/<p>Cele mai recente postari:<\/p>/r $blogfile" $webdir/$domain_name/index.html
 	rm $article_path;
 	rm "$webdir/$webtarget/posts/$basefile/$basefile.md"
 	rm -rf "$webdir/.drafts/$chosen"
 	push
+
 	impose_changes
 }
 
@@ -78,11 +86,11 @@ confirm() { read -erp "Really $1 \"$base\"? (y/N) " choice && echo "$choice" | g
 push() { git add . ; git commit -m "new post" ; git push "https://$gittoken/$gitrepo";}
 
 
-impose_changes() { ssh -i #ssh_key_path  $remotehost -t "cd /var/www;/bin/git pull;/bin/systemctl restart nginx" ;}
+impose_changes() { ssh $remotehost -t "cd /var/www/Pseudot;/bin/git pull;/bin/systemctl restart nginx" ;}
 
 delete() { \
 	indexpath=$webdir/$webtarget/posts/$base.html
-	sed -i "/<div class='entry'>/{:a;N;/<\\/div>/!ba};/id='$base'/d" "$webdir/$www_var_folder_root/index.html"
+	sed -i "/<div class='entry'>/{:a;N;/<\\/div>/!ba};/id='$base'/d" "$webdir/$domain_name/index.html"
 	sed -i "/<div class='article'>/{:a;N;/<\\/div>/!ba};/id='$base'/d" "$webdir/$webtarget/index.html"
 	# Maybe someday
 	sed -i "\@<li>.*<a href=\"$indexpath\">@d" "$indexfile"
@@ -90,7 +98,7 @@ delete() { \
 	push
 	impose_changes
 }
-
+:
 revise() {
 	if [ ! -d "$webdir/.drafts/$chosen" ];then
 	mkdir -p "$webdir/.drafts/${chosen%%.*}/";
@@ -100,28 +108,52 @@ revise() {
 	push
 
 	printf "Revision stored in .drafts. Publish as normal entry when desired.\\n" ;}
+display_help()
+{
+   echo "lb - Utilitary for automating blog management tasks.";
+   echo
+   printf "Usage:\\n  lb a:\\tnew draft\\n  lb e:\\tedit draft\\n  lb p:\\tpublish draft\\n  lb r:\\trevise published entry\\n  lb t:\\tdiscard draft\\n  lb d:\\tdelete published entry\\n\\nBe sure to have the following pattern added to your blog file and blog index:\\n\\n<!-- LB -->\\n\\nNew content will be added directly below that sequence and it is required.\\n"
+}
 
-if [ -z $2 ]
+if [ $# -le 0 ]
 then
 
-echo "You must specify the site's prefix.";
-printf "Available options: \\n\\t1)blog\\n\\t2)programming\\n\\t3)books\\n\\t4)draw\\n\\t5)uc\\n";
+echo "Command syntax: lb [ACTION] [TARGET]"
+echo
+echo "Run the command «lb h» for more information"
 exit
-else
-website="$protocol://$2.$www_var_folder_root";
+# de revizuit bucatica asta
+#else
+#website="$protocol://$2.$domain_name";
 
-webtarget="$2.$www_var_folder_root"
-webtarget_blog_file="$2.$www_var_folder_root/$(date +%Y).html"
-touch $webtarget_blog_file;
+#webtarget="$2.$domain_name"
+#webtarget_blog_file="$2.$domain_name/$(date +%Y).html"
+#touch $webtarget_blog_file;
 
 fi
 
+# separating the main functionalities in regards to the number of parameters
+if [ -z $2 ]
+then
+# one parameter actions
+case "$1" in
+	p*) listandReturn "$webdir"/.drafts/ publish && publish ;;
+	h*) display_help;;
+	*) printf "Usage:\\n  lb a:\\tnew draft\\n  lb e:\\tedit draft\\n  lb p:\\tpublish/finalize draft\\n  lb r:\\trevise published entry\\n  lb t:\\tdiscard draft\\n  lb d:\\tdelete published entry\\n\\nBe sure to have the following pattern added to your RSS feed, blog file and blog index:\\n\\n<!-- LB -->\\n\\nNew content will be added directly below that sequence. This is required.\\n" ;;
+esac
+else
+# multiple parameter actions
 case "$1" in
 	a*) newpost ;;
-	e*) listandReturn "$webdir"/.drafts/ edit && "$EDITOR" "$webdir/.drafts/$chosen/$chosen.md" ;;
-	p*) listandReturn "$webdir"/.drafts/ publish && publish ;;
-	t*) listandReturn "$webdir"/.drafts/ trash && confirm trash && rm -rf "$webdir/.drafts/$chosen" && sed -i "/ \"$base.html\"/d" "$archivefile" ; printf "Draft deleted.\\n" ;;
 	d*) listandReturn "$webdir"/"$webtarget/posts" delete && confirm delete && delete && sed -i "/ \"$base.html\"/d" "$archivefile" ;;
 	r*) listandReturn "$webdir"/"$webtarget/posts" revise && revise ;;
+	e*) listandReturn "$webdir"/.drafts/ edit && "$EDITOR" "$webdir/.drafts/$chosen/$chosen.md" ;;
+	t*) listandReturn "$webdir"/.drafts/ trash && confirm trash && rm -rf "$webdir/.drafts/$chosen" && sed -i "/ \"$base.html\"/d" "$archivefile" ; printf "Draft deleted.\\n" ;;
 	*) printf "Usage:\\n  lb a:\\tnew draft\\n  lb e:\\tedit draft\\n  lb p:\\tpublish/finalize draft\\n  lb r:\\trevise published entry\\n  lb t:\\tdiscard draft\\n  lb d:\\tdelete published entry\\n\\nBe sure to have the following pattern added to your RSS feed, blog file and blog index:\\n\\n<!-- LB -->\\n\\nNew content will be added directly below that sequence. This is required.\\n" ;;
+esac
+
+fi
+# Two parameter actions
+case "$1" in
+
 esac
